name: Docker

on:
  workflow_dispatch:
  
env:
  # Use docker.io for Docker Hub if empty
  DST_REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  DST_IMAGE_NAME: ${{ github.repository }}
  SRC_REGISTRY: docker.io
  SRC_IMAGE_NAME: alpine

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      
      - name: Log into registry ${{ env.SRC_REGISTRY }}
        run: |
          echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u belcebus --password-stdin ${{ env.SRC_REGISTRY}}
          docker pull ${{env.SRC_REGISTRY}}/${{env.SRC_IMAGE_NAME}}:latest
          docker images        

      - name: Retag ${{ env.SRC_REGISTRY }}/${{env.SRC_IMAGE_NAME}}:latest
        run: |
          docker tag ${{ env.SRC_REGISTRY }}/${{env.SRC_IMAGE_NAME}}:latest ${{ env.DST_REGISTRY }}/${{env.DST_IMAGE_NAME}}:1.0.0
      
      - name: Logout ${{ env.SRC_REGISTRY }}
        run: |
          docker logout
      
      - name: Log into registry ${{ env.DST_REGISTRY }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} --password-stdin ${{ env.DST_REGISTRY}}
          docker push ${{ env.DST_REGISTRY }}/${{env.DST_IMAGE_NAME}}:1.0.0
